services:
  next-app:
    build:
      context: ../../test/frontend-little-lewis
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./next:/app/.next
    restart: on-failure
    ports:
      - 3000:3000