version: "3"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000