import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import DesktopNavigation from "@/components/navigation/deskstopNavigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
    children: ReactNode;
}
export default function RootLayout(RootLayoutProps: RootLayoutProps) {
    const { children } = RootLayoutProps;
  return (
    <html lang="fr">
      <body>
      <DesktopNavigation />
      {children}
      </body>
    </html>
  );
}
